[theme]

# Vamos usar a theme Dark

# Theme for the app
# Accepted values (light | dark)
base = "dark"

# Primary accent for interactive elements
# primaryColor = '#7792E3'

# Background color for the main content area
#  backgroundColor = 'bl

# Background color for sidebar and most interactive widgets
# secondaryBackgroundColor = '#52ebca'

# Color used for almost all text
# textColor = 'white'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"

# user_input=st.text_input("You:",key='input') Change color

[server]
enableXsrfProtection = false
